#!/usr/bin/python3

import sys
import time


def is_prime(n):
    if n <= 1:
        return False
    if n <= 3:
        return True
    if n % 2 == 0 or n % 3 == 0:
        return False
    i = 5
    while i * i <= n:
        if n % i == 0 or n % (i + 2) == 0:
            return False
        i += 6
    return True


def factorize(n):
    for i in range(2, n//2 + 1):
        if n % i == 0 and is_prime(i) and is_prime(n//i):
            return (i, n//i)


def main(filename):
    with open(filename, 'r') as file:
        for line in file:
            num = int(line.strip())
            p, q = factorize(num)
            print("{}={}*{}".format(num, p, q))


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: {} <file>".format(sys.argv[0]))
        sys.exit(1)
    main(sys.argv[1])
